import {
    SiPython,
    SiJavascript,
    SiTypescript,
    SiReact,
    SiNextdotjs,
    SiVuedotjs,
    SiAngular,
    SiNodedotjs,
    SiCplusplus,
    SiOpenjdk,
    SiKotlin,
    SiSwift,
    SiRust,
    SiGo,
    SiPhp,
    SiRuby,
    SiScala,
    SiDart,
    SiLua,
    SiPerl,
    SiMysql,
    SiPostgresql,
    SiMongodb,
    SiRedis,
    SiSqlite,
    SiSupabase,
    SiFirebase,
    SiPrisma,
    SiGraphql,
    SiDocker,
    SiKubernetes,
    SiLinux,
    SiUbuntu,
    SiGit,
    SiGithub,
    SiGitlab,
    SiNginx,
    SiGooglecloud,
    SiVercel,
    SiNetlify,
    SiCloudflare,
    SiTerraform,
    SiAnsible,
    SiTensorflow,
    SiPytorch,
    SiOpenai,
    SiHuggingface,
    SiScikitlearn,
    SiKeras,
    SiOpencv,
    SiJupyter,
    SiNumpy,
    SiPandas,
    SiUnity,
    SiUnrealengine,
    SiBlender,
    SiWebgl,
    SiThreedotjs,
    SiSteam,
    SiOculus,
    SiAndroid,
    SiApple,
    SiCss,
    SiFlutter,
    SiIonic,
    SiTailwindcss,
    SiHtml5,
    SiSass,
    SiBootstrap,
    SiWebpack,
    SiVite,
    SiBabel,
    SiEslint,
    SiJest,
    SiFastapi,
    SiDjango,
    SiFlask,
    SiSpring,
    SiLaravel,
    SiExpress,
    SiNestjs,
    SiElectron,
    SiTauri,
    SiRaspberrypi,
    SiArduino,
    SiPostman,
    SiFigma,
    SiNotion,
    SiJetbrains,
    SiVim,
    SiElasticsearch,
} from "react-icons/si";

export const CATEGORY_ICONS = [
    // ─── Languages ───────────────────────────────────────
    { name: "Python", icon: SiPython },
    { name: "JavaScript", icon: SiJavascript },
    { name: "TypeScript", icon: SiTypescript },
    { name: "CPlusPlus", icon: SiCplusplus },
    { name: "Java", icon: SiOpenjdk },
    { name: "Kotlin", icon: SiKotlin },
    { name: "Swift", icon: SiSwift },
    { name: "Rust", icon: SiRust },
    { name: "Go", icon: SiGo },
    { name: "PHP", icon: SiPhp },
    { name: "Ruby", icon: SiRuby },
    { name: "Scala", icon: SiScala },
    { name: "Dart", icon: SiDart },
    { name: "Lua", icon: SiLua },
    { name: "Perl", icon: SiPerl },
    { name: "C", icon: SiCplusplus },
    { name: "C#", icon: SiCplusplus },
    { name: "CSS", icon: SiCss },


    // ─── Frontend ─────────────────────────────────────────
    { name: "React", icon: SiReact },
    { name: "NextJs", icon: SiNextdotjs },
    { name: "Vue", icon: SiVuedotjs },
    { name: "Angular", icon: SiAngular },
    { name: "HTML5", icon: SiHtml5 },
    { name: "TailwindCSS", icon: SiTailwindcss },
    { name: "Sass", icon: SiSass },
    { name: "Bootstrap", icon: SiBootstrap },
    { name: "ThreeJs", icon: SiThreedotjs },
    { name: "WebGL", icon: SiWebgl },

    // ─── Backend ──────────────────────────────────────────
    { name: "NodeJs", icon: SiNodedotjs },
    { name: "Express", icon: SiExpress },
    { name: "NestJs", icon: SiNestjs },
    { name: "FastAPI", icon: SiFastapi },
    { name: "Django", icon: SiDjango },
    { name: "Flask", icon: SiFlask },
    { name: "Spring", icon: SiSpring },
    { name: "Laravel", icon: SiLaravel },
    { name: "GraphQL", icon: SiGraphql },

    // ─── Databases ────────────────────────────────────────
    { name: "MySQL", icon: SiMysql },
    { name: "PostgreSQL", icon: SiPostgresql },
    { name: "MongoDB", icon: SiMongodb },
    { name: "Redis", icon: SiRedis },
    { name: "SQLite", icon: SiSqlite },
    { name: "Supabase", icon: SiSupabase },
    { name: "Firebase", icon: SiFirebase },
    { name: "Prisma", icon: SiPrisma },
    { name: "Elasticsearch", icon: SiElasticsearch },

    // ─── AI / ML / Data ───────────────────────────────────
    { name: "TensorFlow", icon: SiTensorflow },
    { name: "PyTorch", icon: SiPytorch },
    { name: "OpenAI", icon: SiOpenai },
    { name: "HuggingFace", icon: SiHuggingface },
    { name: "ScikitLearn", icon: SiScikitlearn },
    { name: "Keras", icon: SiKeras },
    { name: "OpenCV", icon: SiOpencv },
    { name: "Jupyter", icon: SiJupyter },
    { name: "Numpy", icon: SiNumpy },
    { name: "Pandas", icon: SiPandas },

    // ─── VR / AR / Game Dev ───────────────────────────────
    { name: "Unity", icon: SiUnity },
    { name: "UnrealEngine", icon: SiUnrealengine },
    { name: "Blender", icon: SiBlender },
    { name: "Oculus", icon: SiOculus },
    { name: "Steam", icon: SiSteam },

    // ─── Mobile ───────────────────────────────────────────
    { name: "Android", icon: SiAndroid },
    { name: "Apple", icon: SiApple },
    { name: "Flutter", icon: SiFlutter },
    { name: "Ionic", icon: SiIonic },

    // ─── DevOps / Cloud ───────────────────────────────────
    { name: "Docker", icon: SiDocker },
    { name: "Kubernetes", icon: SiKubernetes },
    { name: "GoogleCloud", icon: SiGooglecloud },
    { name: "Vercel", icon: SiVercel },
    { name: "Netlify", icon: SiNetlify },
    { name: "Cloudflare", icon: SiCloudflare },
    { name: "Terraform", icon: SiTerraform },
    { name: "Ansible", icon: SiAnsible },
    { name: "Nginx", icon: SiNginx },
    { name: "Linux", icon: SiLinux },
    { name: "Ubuntu", icon: SiUbuntu },

    // ─── Tools ────────────────────────────────────────────
    { name: "Git", icon: SiGit },
    { name: "GitHub", icon: SiGithub },
    { name: "GitLab", icon: SiGitlab },
    { name: "JetBrains", icon: SiJetbrains },
    { name: "Vim", icon: SiVim },
    { name: "Postman", icon: SiPostman },
    { name: "Figma", icon: SiFigma },
    { name: "Notion", icon: SiNotion },
    { name: "Webpack", icon: SiWebpack },
    { name: "Vite", icon: SiVite },
    { name: "Babel", icon: SiBabel },
    { name: "ESLint", icon: SiEslint },
    { name: "Jest", icon: SiJest },
    { name: "Electron", icon: SiElectron },
    { name: "Tauri", icon: SiTauri },

    // ─── Hardware / IoT 
    { name: "RaspberryPi", icon: SiRaspberrypi },
    { name: "Arduino", icon: SiArduino },

];